// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRU4qFDglFL819LwiGb-m3T-npfaSHdaM',
    appId: '1:486155325406:web:bfe645db850510ad63574f',
    messagingSenderId: '486155325406',
    projectId: 'fix-bisa',
    authDomain: 'fix-bisa.firebaseapp.com',
    storageBucket: 'fix-bisa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6sgAiik1vxMMPF2-YlcuN6lNJZUFefdE',
    appId: '1:486155325406:android:a6420ca989e6fb7463574f',
    messagingSenderId: '486155325406',
    projectId: 'fix-bisa',
    storageBucket: 'fix-bisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkApaRPQ8dbG4VPsPcw697gTReC3lELrc',
    appId: '1:486155325406:ios:86ac2aa134f389b563574f',
    messagingSenderId: '486155325406',
    projectId: 'fix-bisa',
    storageBucket: 'fix-bisa.appspot.com',
    iosClientId: '486155325406-sfrjn40ukdg1qnj4o8nc2of4tqqr0htq.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkApaRPQ8dbG4VPsPcw697gTReC3lELrc',
    appId: '1:486155325406:ios:86ac2aa134f389b563574f',
    messagingSenderId: '486155325406',
    projectId: 'fix-bisa',
    storageBucket: 'fix-bisa.appspot.com',
    iosClientId: '486155325406-sfrjn40ukdg1qnj4o8nc2of4tqqr0htq.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRU4qFDglFL819LwiGb-m3T-npfaSHdaM',
    appId: '1:486155325406:web:6226fc05218f39d263574f',
    messagingSenderId: '486155325406',
    projectId: 'fix-bisa',
    authDomain: 'fix-bisa.firebaseapp.com',
    storageBucket: 'fix-bisa.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBRU4qFDglFL819LwiGb-m3T-npfaSHdaM',
    appId: '1:486155325406:web:43dcc0c7562b5f1d63574f',
    messagingSenderId: '486155325406',
    projectId: 'fix-bisa',
    authDomain: 'fix-bisa.firebaseapp.com',
    storageBucket: 'fix-bisa.appspot.com',
  );
}
